### ISSUE TITLE
Problem when using DbModule instead of ormconfig.json

### ISSUE THREAD

**Issue by nihil-pro** [ambroiseRabier/typeorm-nestjs-migration-example#1]
Hi 
I get and error when i try typeorm:migrate <Something>

```
`konstantinroman@MacBook-Pro store % npm run typeorm:migrate UserEmail

> store@0.0.1 typeorm:migrate
> npm run typeorm migration:generate -- -n "UserEmail"


> store@0.0.1 typeorm /Users/konstantinroman/Desktop/Important projects/store
> ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/ormconfig.ts "migration:generate" "-n" "UserEmail"

Error during migration generation:
Error: Cannot find module '/Users/konstantinroman/Desktop/Important projects/store/src/ormconfig.ts'
Require stack:
- /Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/connection/ConnectionOptionsReader.js
- /Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/globals.js
- /Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/commands/SchemaSyncCommand.js
- /Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._resolveFilename (/Users/konstantinroman/Desktop/Important projects/store/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at ConnectionOptionsReader.<anonymous> (/Users/konstantinroman/Desktop/Important projects/store/src/connection/ConnectionOptionsReader.ts:111:40)
    at step (/Users/konstantinroman/Desktop/Important projects/store/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/konstantinroman/Desktop/Important projects/store/node_modules/tslib/tslib.js:124:57)
    at /Users/konstantinroman/Desktop/Important projects/store/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/connection/ConnectionOptionsReader.js',
    '/Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/globals.js',
    '/Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/commands/SchemaSyncCommand.js',
    '/Users/konstantinroman/Desktop/Important projects/store/node_modules/typeorm/cli.js'
  ]
}
```
`
Can you explain please how can i use migrations with my db module?

```
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { ConfigModule, ConfigService } from '@nestjs/config'

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get('POSTGRES_HOST'),
        port: configService.get('POSTGRES_PORT'),
        username: configService.get('POSTGRES_USER'),
        password: configService.get('POSTGRES_PASSWORD'),
        database: configService.get('POSTGRES_DB'),
        entities: [__dirname + '/../**/**.entity{.ts,.js}'],
        synchronize: false,
        migrationsRun: true,
        logging: true,
        logger: 'file',
        migrations: [__dirname + '/migrations/**/*{.ts,.js}'],
        cli: { migrationsDir: 'src/migrations' }
      })
    })
  ]
})
export default class DatabaseModule {}
```

**Comment by ambroiseRabier** [comment]
Hello, sorry this is a one shot example project, I do not plan to maintain it up to date, mainly because I stopped working on the project making use of that.

The original project was working, so you either use a more recent version of some dependencies, that introduced breaking changes. Or your project is somehow differently configured. That is my guess, best luck in resolving it !
